### ISSUE TITLE
Comment - Hooks - required

### ISSUE THREAD

**Issue by chrisjantzen** [feathers-plus/docs.feathers-plus.org#14]
Comment - Hooks - required

I think some more info on how this works with find/get would be useful. Looking at the code it verifies that the property exists in the data object when patching/updating/creating but it is not clear how this would work on find/get. At first I assumed it would check the queries parameters but it seems like it still checks the data object, which to my knowledge has no use on the find/get hooks?

**Comment by eddyystop** [comment]
It's not intended to work work get or find, though the code allows it and the docs say it does.

Could you please create an issue on @feathers-plus/feathers-hooks-common? Thanks in advance.
