### ISSUE TITLE
Comment - Hooks - fastJoin

### ISSUE THREAD

**Issue by DaniSchenk** [feathers-plus/docs.feathers-plus.org#15]
> Read the guide for more information on the arguments.

link is broken

**Comment by eddyystop** [comment]
https://feathers-plus.github.io/v1/feathers-hooks-common/index.html

**Comment by eddyystop** [comment]
Thanks.

**Comment by eddyystop** [comment]
https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#fastJoin

**Comment by eddyystop** [comment]
Fixed 2018/02/05
