### ISSUE TITLE
Comment - Hooks - iff

### ISSUE THREAD

**Issue by bertho-zero** [feathers-plus/docs.feathers-plus.org#33]
Comment - Hooks - iff

I think we can add a `.elseif`, like `.else`.

I know it's possible, but for hooks to be indented as they would be with code it would be necessary to add this method.

```js
iff(
  isAction('updateProfile'),
  /**/
).elseif(
  isAction('changePassword'),
  /**/
).else(
  /**/
)
```

instead of:

```js
iff(
  isAction('updateProfile'),
  /**/
).else(
  iff(
    isAction('changePassword'),
    /**/
  )
  .else(
    /**/
  )
)
```

**Comment by eddyystop** [comment]
It can also be argued that a `case` syntax should be introduced.

My feeling is that this all leads us down the rabbit hole to reimplementing more JS structures. This isn't needed as `combine` can be used.
```js
context => {
  if (...) {
    return combine([hook1, hook2, ...])(context);
  } elseif (...) {
    return combine([hook11, hook12,...])(context);
  }
}
```

The questions on Slack already indicate people can't find hooks they are looking for, even with the tag-oriented x-ref in the docs. More hooks will increase the problem. Each hook also adds unneeded additional cognative load, while `combine` and JS can implement complicated decisions.

The hooks passed to `combine` can also be a mutable array, allowing dynmaic ordering of the hooks.

I'll be adding an extensive section to the Guide and likely the API to highlight `combine`.
