### ISSUE TITLE
Comment (Data Logically Removed After Update) - Hooks - softDelete2

### ISSUE THREAD

**Issue by berviantoleo** [feathers-plus/docs.feathers-plus.org#46]
Hello,

I want to ask why my data logically deleted after update using PUT.

My environment:
```
feathers-hook-common: 4.16.3
feathers-sequelize: 3.1.2
sequelize: 4.38.0
```

My model (just for example):
```
... // Any Data
text: Text
deleted: Boolean, allowNull: false, default: true
deletedAt: Date, allowNull: true
```

My services hooks:
```
const { softDelete2 } = require('feathers-hooks-common');

const optionsBefore = {
  deletedAt: 'deletedAt',
  keepOnCreate: true,
  skipProbeOnGet: false,
  allowIgnoreDeletedAt: true
};

const optionsAfter = {
  deletedAt: 'deletedAt',
  skipProbeOnGet: false,
  allowIgnoreDeletedAt: true
};

module.exports = {
  before: {
    all: [softDelete2(optionsBefore)],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  after: {
    all: [softDelete2(optionsAfter)],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },

  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};
```

I try update spesific id using tools Postman,
My data like this:
PUT {host}/services/{id}
```
... (my data)
deleted: false
```

After I want update the data again, It return data logically deleted. Also when I update with deleted: 0. 
When I send data within deletedAt: -1, also after I try to update data again, it return data logically deleted. Some my trial is:
1. Make deleted: nullable
- When send data without deleted, it will deleted logically too (because deleted becomes null)
- When send data with deleted: true/0. It will deleted logically too.

Maybe I miss to how to use softDelete2()?

__Updated__:

After I read the source : https://github.com/feathers-plus/feathers-hooks-common/blob/b4adf36c61617e0e072a2e5c11de02ef83e44756/lib/services/soft-delete-2.js#L155

I think I miss the focus of softDelete2, It's different with softDelete() that checking delete data, the softDelete2() check deleteAt.

I want to change my question. If I use sequelize & MySQL,
1. what type of data I should use (for deleteAt), should be STRING/TEXT?
2. How I must send the data using REST so it will not deleted?

**Comment by eddyystop** [comment]
1. `deletedAt` (not deleteAt) is a signed integer i.e. https://github.com/feathers-plus/feathers-hooks-common/blob/master/lib/services/soft-delete-2.js#L174

2. I don't understand the question. By default no record is deleted on any update, patch, remove call.

**Comment by berviantoleo** [comment]
Thanks.

For question 2, I think the property of deletedAt must be not null. I must change the model. When I update and not send deletedAt parameter, (I don't know where it is) it will assume deletedAt null, then set deleted into null so it make logically deleted.
I still find another things why when updated data it also logically deleted (column deletedAt also updated).

**Comment by eddyystop** [comment]
`softDelete` uses the field `deleted`. `softDelete2` uses the field `deletedAt`. You have convert your user-entity records when migrating from `softDelete` to `softDelete2`.

Does this answer you question?

**Comment by berviantoleo** [comment]
Yes, I think that is enough for me.
