### ISSUE TITLE
Comment - Hooks - sifter

### ISSUE THREAD

**Issue by gerwintown** [feathers-plus/docs.feathers-plus.org#54]
Comment - Hooks - sifter

The guide's spec table says "no" for "before" and "yes" for "after," but the example(s) contradict this showing the hook used as a before hook.

**Comment by eddyystop** [comment]
Its an after hook. https://github.com/feathers-plus/feathers-hooks-common/blob/master/lib/services/sifter.js#L9

The example will be changed the next refresh of the repo.
