### ISSUE TITLE
Comment - Hooks - skipRemainingHooks

### ISSUE THREAD

**Issue by cdimitroulas** [feathers-plus/docs.feathers-plus.org#56]
Comment - Hooks - skipRemainingHooks

What does this warning/note mean?
`! The database call itself will be shipped only if context.result has been set.`

Is this referring to the fact that the service call is skipped if `context.result` is set? If so, then I propose this note is amended to read:
`! The service call will only be skipped if context.result has been set manually.`

**Comment by cdimitroulas** [comment]
PR made for the change proposed in the issue

**Comment by eddyystop** [comment]
Thanks!
