### ISSUE TITLE
outdated jsonschema.net example

### ISSUE THREAD

**Issue by MohammedFaragallah** [feathers-plus/docs.feathers-plus.org#58]
I would like to thank you for the great work with feathers-plus you took a great framework to a whole new level.
I'm new to JSON schema and jsonschema.net changed their design/options and I feel really lost any chance to update the docs with the new options or suggest good resources? then i will try to submit a PR with the update.

**Comment by eddyystop** [comment]
This is my go-to tutorial https://code.tutsplus.com/tutorials/validating-data-with-json-schema-part-1--cms-25343 . The common validateSchema hook uses this author's ajv.
