### ISSUE TITLE
Comment - Hooks - validate

### ISSUE THREAD

**Issue by germanp** [feathers-plus/docs.feathers-plus.org#64]
Comment - Hooks - validate

Hi,

I've noted that the guide section with validation examples (https://feathers-plus.github.io/v1/feathers-hooks-common/guide.html#Validate) includes an example of validation with another package (https://github.com/eddyystop/feathers-hooks-validate-joi), I first tought that it used validateSchema from this  project but it was wrong, validateSchema from this project uses ajv.

**Comment by eddyystop** [comment]
The guide shows Joi as an alternative. Some people prefer using Walmart's option.

JSON-schema is industry standard, used by Swagger and the OpenAPI initiative ( https://github.com/OAI/OpenAPI-Specification ). It also enables cli+ to convert schemas to database models.

For these reasons we focus on JSON-schema.
