### ISSUE TITLE
Comment - Hooks - iff

### ISSUE THREAD

**Issue by butilities** [feathers-plus/docs.feathers-plus.org#65]
Comment - Hooks - iff
When returning SKIP from hook functions, it will throw 'method returned invalid hook object'

eg:

```
...
before:{
 find: [iff(isProvider('external'), async hook =>{
              hook.result = { code: 0 };
              return require('@feathersjs/feathers').SKIP;
          })]
}
...
```
Please advice

**Comment by eddyystop** [comment]
SKIP was introduced with a badly designed PR for @feathersjs/feathers, not for the common hooks. SKIP has issues:
- You cannot both change the hook context and SKIP in one hook.
- There is no way to skip the after hooks from within the before hooks.
- At **best** SKIP skips the chain of hooks within the `iff`. The hooks after the `iff` will still run, **which may be what you are trying to accomplish.**

I don't know the details of the issue you are running into but I doubt anything can be done about it within the common hooks. I suggest you write a custom hook which does not use `iff`.
