### ISSUE TITLE
Comment - Hooks - actOnDefault

### ISSUE THREAD

**Issue by haywhyze** [feathers-plus/docs.feathers-plus.org#66]
Hooks `hook1`, `hook3` and `hook5` will run “normally”, mutating **content.result**.
Hooks `hook2` and `hook4` will mutate context.dispatch.

Just pointing out a typo. I believe the bolded text in the above snippet from the docs should be 
**context.result**

**Comment by eddyystop** [comment]
Please submit a PR. That's how open source us supposed to work.

**Comment by haywhyze** [comment]
Okay. Done here => [#67](https://github.com/feathers-plus/docs/pull/67)
