### ISSUE TITLE
Comment - Hooks - stashBefore

### ISSUE THREAD

**Issue by acklavidian** [feathers-plus/docs.feathers-plus.org#78]
Comment - Hooks - stashBefore
Perhaps a pedantic nitpick but this example imports "patch" but I think it meant to import "stashBefore". 
```javascript
const { patch } = require('feathers-hooks-common');
module.exports = { before: {
  patch: stashBefore()
} };
```

**Comment by marshallswain** [comment]
Thanks @acklavidian.  I've fixed this in the new docs.
